[build]
  # Directory where the build artifacts are located
  publish = "."

[build.environment]
  # Node.js version for build environment
  NODE_VERSION = "18"

[[headers]]
  # Define custom headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self';"

[[headers]]
  # Cache static assets for 1 year
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache images for 1 month
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  # Cache CSS and JS for 1 week
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  # Cache HTML for 1 hour
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  # Redirect root to index.html
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # Handle 404 errors
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling
[[forms]]
  # Contact form
  name = "contact"
  action = "/contact"
  method = "POST"
  
  # Form fields
  [forms.fields]
    name = "required"
    email = "required email"
    phone = "tel"
    subject = "required"
    message = "required"

# Prerender settings for better SEO
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugin configurations
[[plugins]]
  package = "netlify-plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "."
    exclude = [
      "assets/images/placeholder/*"
    ]

# Environment variables
[context.production.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.111.3"

# Performance optimizations
[build.command]
  # Add any build commands here if needed
  command = "echo 'Static site - no build needed'"

# Security headers for forms
[[headers]]
  for = "/contact"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
